### ISSUE TITLE
Wrong path for lib in Linux

### ISSUE THREAD

**Issue by Thuener** [JuliaOpt/Xpress.jl#14]
ERROR: LoadError: error compiling __init__: error compiling Env: could not load library "/opt/xpressmp/lib/libxprs.so"
libxprl.so.x8.0: cannot open shared object file: No such file or directory

**Comment by joaquimg** [comment]
The lib exists and it is in the path?

What are the values of the following env variables:
`XPRESSDIR`, `PATH`, `LD_LIBRARY_PATH`, `CLASSPATH` and `XPRESS`
All of them must be correctely set for a complete installation:

```
setenv XPRESSDIR your_xpress_install_dir
setenv PATH $XPRESSDIR/bin:$PATH
setenv LD_LIBRARY_PATH $XPRESSDIR/lib:$LD_LIBRARY_PATH
setenv CLASSPATH $XPRESSDIR/lib/xprs.jar:$CLASSPATH
setenv CLASSPATH $XPRESSDIR/lib/xprb.jar:$CLASSPATH
setenv CLASSPATH $XPRESSDIR/lib/xprm.jar:$CLASSPATH
setenv XPRESS $XPRESSDIR/bin
```

**Comment by Thuener** [comment]
It was a problem with my shell(fish-shell) but the v0.4.0 version still gives problem with the license:
ERROR: InitError: Xpress licensing error 1: The license file (/opt/xpressmp/bin/../lib/xpauth.xpr) could not be read. No such file or directory. Please ensure you have installed it according to the instructions in the FICO Xpress READMEs.
 in #userlic#21(::Xpress.#emptyliccheck, ::String, ::Function) at /home/thuener/.julia/v0.5/Xpress/src/xprs_userlic.jl:75
 in __init__() at /home/thuener/.julia/v0.5/Xpress/src/Xpress.jl:95
 in _include_from_serialized(::String) at ./loading.jl:150
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:187
 in require(::Symbol) at ./loading.jl:423
during initialization of module Xpress

But with the latest version this issue is solved. Thanks, I'm closing this issue.
