### ISSUE TITLE
QP solving time

### ISSUE THREAD

**Issue by YutingMou** [JuliaOpt/Xpress.jl#19]
I observed a strange behavior when I was solving a small QP:
I put solve(m) between tic() toq() to measure the solving time, it turned out to be 50 seconds. But When I switch to Gurobi, the solving time was 2 seconds, which is reasonable. 
I also tested LP and MILP, Xpress and Gurobi were similar in terms of solving time.

**Comment by joaquimg** [comment]
Do you have a minimal working example for that?
That might be due to the way the QPs are being passed to the solver.

**Comment by YutingMou** [comment]
The following is an example adapted from the website of yalmip  (https://yalmip.github.io/tutorial/quadraticprogramming/).
Since getsolvetime() does not work in Xpress, I only  use tic() and toq(). 
It takes Xpress 17.959449473 seconds, while it takes Gurobi 3.297242234 seconds. 

using JuMP
MySolver = "Gurobi"

if MySolver == "Xpress"
    using Xpress
    SolverChoice = Xpress.XpressSolver()
elseif MySolver == "Gurobi"
    using Gurobi
    SolverChoice = GurobiSolver()
else
    println("solver not defined")

end

m = Model(solver = SolverChoice)


x = [1 2 3 4 5 6]';
t = (0:0.02:100*pi)';
A = [sin.(t); sin.(2*t); sin.(3*t); sin.(4*t); sin.(5*t); sin.(6*t)];
myerror = (-4+8*rand(length(t),1));
y = A'*x+myerror;

@variables m begin
    xhat[1:6]
    residuals[1:length(t)]
end
@constraints m begin
    residuals .== y-A'*xhat
end
@objective(m, Min, sum((residuals[i] -1)^2 for i = 1:length(t)))
tic()
status= solve(m)
#solvetime = getsolvetime(m)
solvetime = toq()
println("It takes ", MySolver, " ", solvetime, " seconds")

**Comment by odow** [comment]
Closing as stale. If you can re-produce this on latest release, please open.
