### ISSUE TITLE
could not load library "libxprs.dylib" in Jupyter environment

### ISSUE THREAD

**Issue by kdheepak** [JuliaOpt/Xpress.jl#21]
When I run `using Xpress` in a jupyter notebook or in jupyter lab, I get the following error.

```julia
using Xpress

InitError: error compiling __init__: error compiling Env: could not load library "libxprs.dylib"
dlopen(libxprs.dylib, 1): image not found
during initialization of module Xpress
```

When I run this in the command line where I started the notebook (in the same shell session) I do not get any error. Does anyone know what might be going on?

**Comment by joaquimg** [comment]
Which version of julia, Xpress.jl and Xpress Optimizer are you using?
Have you installed Xpress with all the correct enviroment variables?
Were there errors on installation or during build process of the julia lib?

**Comment by kdheepak** [comment]
@joaquimg thanks for the quick reply. I did more experimenting, and I think it's not related to this Julia package issue. I have `DYLD_FALLBACK_LIBRARY_PATH` set in my bash_profile, and I think when Jupyter starts it removes that environment variable. I tested this in Python and Julia in and outside a Jupyter environment. I'm not sure if this is a Mac specific issue at this point, but I'll close this here for now.

**Comment by mkhraijah** [comment]
I has a similar problem. The fix was to change line 12 in [Xpress.jl](https://github.com/jump-dev/Xpress.jl/blob/master/src/Xpress.jl) to:

`const depsjl_path = abspath(joinpath(@__DIR__, "..", "deps", "deps.jl"))`

This change fixed the problem. It seems there is an issue reading ".." in MacOC
