### ISSUE TITLE
Issue with duplicate terms in linear part of objective function?

### ISSUE THREAD

**Issue by tkoolen** [JuliaOpt/Xpress.jl#22]
Looks similar to https://github.com/JuliaOpt/Gurobi.jl/pull/125/files/41cc64dbacf1293ed418a4c301b078fc51e9dc35#r203478342:

https://github.com/JuliaOpt/Xpress.jl/blob/8e59ffad3696b4636558827d3ca0eedd05123cff/src/MOIWrapper.jl#L280

**Comment by joaquimg** [comment]
we can just replace by `obj[colvec[i]] `+= coefvec[i]`
right?

**Comment by tkoolen** [comment]
Yep, think so.
