### ISSUE TITLE
Xpress - Julia terminal log

### ISSUE THREAD

**Issue by KSepetanc** [JuliaOpt/Xpress.jl#39]
I am running Julia - JuMP - Xpress on Windows and Xpress solves my model. I can acquire results.
However, I don't get any solver progress log in terminal. Running Xpress looks like:
Julia>
Julia> 

This is highly inconvenient. Am I missing some parameter or is there fix for this?

**Comment by joaquimg** [comment]
Hi!
Sorry for the delay.
Xpress C interface is not able to send the log to the screen in Windows OS specifically.
You have two options:
1) use the file log, and look at it. (use setlogfile function)
2) implement a callback to print the log (use set_callback_message! function https://github.com/JuliaOpt/Xpress.jl/blob/master/src/xprs_callbacks.jl, you will need to check detail in the manual)

**Comment by odow** [comment]
Is there any way to se the XPRS_VERBOSE parameter? 
x-ref: https://discourse.julialang.org/t/unable-to-use-setparam-for-xpress-under-jump/26804/6

**Comment by joaquimg** [comment]
The parameter is called OUTPUTLOG and it won't work as expected in windows as mentioned above.

**Comment by joaquimg** [comment]
Some details on how to use the file:
```julia
# Given a model JuMP model (Xpress no attached)
# first attach the Xpress solver

# Then switch on the OUPUTLOG parameter
Xpress.setparam!(backend(model).optimizer.model.inner, Xpress.XPRS_CONTROLS_DICT[:OUTPUTLOG], 1)

# Finally, enable the log file
Xpress.setlogfile(backend(model).optimizer.model.inner, "path_to\\my2.log")
```

**Comment by joaquimg** [comment]
Now this is simplified and explained in docs
