### ISSUE TITLE
New MOI Wrapper

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/Xpress.jl#40]
Follow https://github.com/JuliaOpt/Gurobi.jl/pull/216

**Comment by joaquimg** [comment]
link the PR to https://github.com/JuliaOpt/MathOptInterface.jl/issues/736

cc @jdlara

**Comment by jd-lara** [comment]
Ok, as soon as the tests pass I will PR into it.

**Comment by joaquimg** [comment]
solved by #43
