### ISSUE TITLE
typo for MOI_wrapper.jl in Xpress.jl line 93?

### ISSUE THREAD

**Issue by NLaws** [JuliaOpt/Xpress.jl#51]
Should [line 93 of Xpress.jl](https://github.com/JuliaOpt/Xpress.jl/blob/b0b866c9ebad00bdc98e506b0e314cfd7140ce0e/src/Xpress.jl#L93) have **include("MOI/MOI_wrapper.jl")** instead of 
```
include("MOI/MOI_Wrapper.jl")
```
? (lower-case "wrapper")

This error came up with:
```
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
```
and 
```
pkg> status
  [4076af6c] JuMP v0.20.1
  [b8f27783] MathOptInterface v0.9.9
  [9e70acf3] Xpress v0.9.1 #jg/new_interface (https://github.com/JuliaOpt/Xpress.jl.git)
```
when 
```
using Xpress
```
I get 
```
LoadError: could not open file ~/.julia/packages/Xpress/IzhEI/src/MOI/MOI_Wrapper.jl
```
with traceback leading to
```
in expression starting at ~/.julia/packages/Xpress/IxhEI/src/Xpress.jl:93
```
https://github.com/JuliaOpt/Xpress.jl/blob/b0b866c9ebad00bdc98e506b0e314cfd7140ce0e/src/Xpress.jl#L93

**Comment by joaquimg** [comment]
solved by #43
