### ISSUE TITLE
Fix the need to re-partition the cached solution after solve

### ISSUE THREAD

**Issue by odow** [JuliaOpt/Xpress.jl#62]
https://github.com/JuliaOpt/Xpress.jl/blob/319c200bc81f96a023e41e37575d1f775039f26f/src/MOI/MOI_wrapper.jl#L2032-L2040

Suggested way forward is:
 - Have an underlying cache to the full vector
 - Construct two views for the linear and quadratic parts

**Comment by joaquimg** [comment]
solved by #75
