### ISSUE TITLE
Document setting attributes using `set_optimizer_attributes` or `optimizer_with_attributes`

### ISSUE THREAD

**Issue by kdheepak** [JuliaOpt/Xpress.jl#68]
The JuMP documentation says that a user can use `optimizer_with_attributes` which calls `set_optimizer_attribute`.

https://github.com/JuliaOpt/JuMP.jl/blob/13ad5db156210f805699e8a1004610d60bc3be3b/src/JuMP.jl#L56-L89

~Current Xpress.jl does not implement `set_optimizer_attribute`.~

It seems that we don't need to implement `set_optimizer_attribute` but currently the attributes don't propogate to the actual model? Maybe I'm missing something or just don't know how to do this. I'm opening this issue so that I can keep track and at the very least submit a PR for documentation.

**Comment by kdheepak** [comment]
Here is an example of how to set XPRESS attributes. All Xpress attributes are currently defined as `const` values generated from Clang.jl and in `Xpress.Lib.XPRS_*`. For e.g. `Xpress.Lib.XPRS_MIPRELSTOP` is the param to set `miprelstop`.

```julia

miprelstop = 0.1
logfile = ""

    model = Model(
        optimizer_with_attributes(
            Xpress.Optimizer,
            JuMP.MOI.RawParameter(Xpress.Lib.XPRS_MIPRELSTOP) => Float64(miprelstop),
            JuMP.MOI.RawParameter(:logfile) => logfile,
        )
    )

    @variable(model, 0 <= x)
    @variable(model, 0 <= y, binary = true)
    @variable(model, 0 <= z, integer = true)
    @objective(model, Max, 1.1x + 2y + 5z)
    @constraint(model, 1x + 5y + 2z <= 3)

    JuMP.optimize!(model)

    @show JuMP.objective_value(model)

    @show MOI.get(model.moi_backend.optimizer, MOI.RawParameter(Xpress.Lib.XPRS_MIPRELSTOP))
    @show MOI.get(model.moi_backend.optimizer, MOI.RawParameter(:logfile))

```

This currently does not work, because `MOI.empty!` creates a new `XpressProblem` when `set(model, ::RawParameter, ::T)` was called on an old `XpressProblem`. The solution referenced in the PR above stores all values that are `set` in the `params` dictionary, and on calling `empty!` after creating the new `XpressProblem` we re-`set` the parameters with the values in the `params` dictionary.

The alternative is to not create a new `XpressProblem` on calling `empty!`. Instead, we would have to use the same `XpressProblem` instance but call `destroyprob` to manually free memory. But this means taht we cannot use the `finalize` calls to `destroyprob`, and may accidentally leak memory (since the user may not call `empty!` when done with solving a model.

**Comment by odow** [comment]
Note that `RawParameter` _must_ accept strings. This is an oversight in the current MOI version. We will be making a breaking change to change `RawParameter` to 
```Julia
struct RawParameter <: AbstractOptimizerAttribute
    name::String
end
```

I suggested a way forward here: https://github.com/JuliaOpt/Xpress.jl/pull/44#discussion_r373182827, but it didn't seems to get implemented

**Comment by kdheepak** [comment]
Fixed in https://github.com/JuliaOpt/Xpress.jl/pull/69/commits/c8b7c368105ce4f0c70a92e5bbe259e4465d10e2 and https://github.com/JuliaOpt/Xpress.jl/pull/69/commits/c0726bf0f196020316f59cce65178d0d7db34eba.

**Comment by kdheepak** [comment]
And all tests pass too.

![Screen Shot 2020-02-25 at 2 08 02 PM](https://user-images.githubusercontent.com/1813121/75287776-40352a80-57d8-11ea-9a6c-695bc1615266.png)

This example now looks like this:

```julia
using Xpress
using JuMP

miprelstop = 0.1
logfile = ""

model = Model(
    optimizer_with_attributes(
        Xpress.Optimizer,
        JuMP.MOI.RawParameter("MIPRELSTOP") => Float64(miprelstop),
        JuMP.MOI.RawParameter("logfile") => logfile,
    )
)

@variable(model, 0 <= x)
@variable(model, 0 <= y, binary = true)
@variable(model, 0 <= z, integer = true)
@objective(model, Max, 1.1x + 2y + 5z)
@constraint(model, 1x + 5y + 2z <= 3)

JuMP.optimize!(model)

@show JuMP.objective_value(model)

@show MOI.get(model.moi_backend.optimizer, MOI.RawParameter("MIPRELSTOP"))
@show MOI.get(model.moi_backend.optimizer, MOI.RawParameter("logfile"))
```

I stripped the `XPRS_` from the names.
